#!/usr/bin/env node
// Regenerates design/theme.css (shadcn-style HSL CSS variables) from design/tokens.json
// and prints a WCAG contrast report, so ports never hand-convert hex → HSL.
// Usage: node design/build-theme.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);

function toHsl(hex) {
  const [r, g, b] = rgb(hex);
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const d = max - min;
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;
  if (d) {
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
    h *= 60;
  }
  const f = (n) => +n.toFixed(1);
  return `${f(h)} ${f(s * 100)}% ${f(l * 100)}%`;
}

function luminance(hex) {
  const [r, g, b] = rgb(hex).map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

const block = (selector, theme, extra) =>
  [
    `  ${selector} {`,
    ...Object.entries(tokens.themes[theme]).map(([k, v]) => `    --${k}: ${toHsl(v)}; /* ${v} */`),
    ...extra.map((line) => `    ${line}`),
    '  }',
  ].join('\n');

const css = `/* Generated by design/build-theme.mjs from design/tokens.json — do not edit by hand. */
/* Dark is the :root default; add class="light" on <html> for the light theme.       */
@layer base {
${block(':root', 'dark', [`--radius: ${tokens.radius.base};`, 'color-scheme: dark;'])}

${block('.light', 'light', ['color-scheme: light;'])}
}
`;
writeFileSync(join(here, 'theme.css'), css);

let failures = 0;
for (const theme of ['dark', 'light']) {
  const t = tokens.themes[theme];
  const rows = [];
  const check = (label, fg, bg) => {
    const ratio = contrast(fg, bg);
    if (ratio < 4.5) failures++;
    rows.push(`${ratio < 4.5 ? '✗' : '✓'} ${label.padEnd(34)} ${ratio.toFixed(2)}`);
  };
  for (const k of ['foreground', 'muted-foreground', 'subtle-foreground', 'primary', 'destructive', 'success', 'warning', 'info', 'tertiary']) {
    check(`${k} on card`, t[k], t.card);
    check(`${k} on muted`, t[k], t.muted);
  }
  for (const k of ['primary', 'destructive', 'success', 'warning', 'info', 'tertiary']) {
    check(`${k}-foreground on ${k}`, t[`${k}-foreground`], t[k]);
  }
  check('code-foreground on code', t['code-foreground'], t.code);
  console.log(`\n[${theme}]\n${rows.join('\n')}`);
}
console.log(`\nwrote design/theme.css — ${failures ? `${failures} pair(s) below 4.5:1` : 'all pairs ≥ 4.5:1 (WCAG AA)'}`);
process.exitCode = failures ? 1 : 0;
